### ISSUE TITLE
Additional Auction properties

### ISSUE THREAD

**Issue by irealworlds** [iRealWorlds/licirom#17]
- [ ] Reserve price
- [ ] Minimum bidding increment
- [ ] Starting point
- [ ] Starting time
- [ ] Duration

**Comment by irealworlds** [comment]
@trupples Backend (including endpoints)
@Slice29 Frontend implementation

Use existing branch `dev/auctions`.

**Comment by trupples** [comment]
Will use EndTime instead of Duration

**Comment by trupples** [comment]
Implemented in 6562b9ebf6aadaf4c8ff4603be62707e45cf59f9, 1f1342ccda6739e2c8246faaf640c6d0ed4fa2c0, 42eb9f39a3c144a527a16ec6131e77c402794aa3
