### ISSUE TITLE
Restrictions on bidding

### ISSUE THREAD

**Issue by irealworlds** [iRealWorlds/licirom#23]
- StartingTime is in the future
- EndingTime is in the past
- CurrentStatus is not Approved

**Comment by trupples** [comment]
For reference, the checks currently implemented in the backend are found here: https://github.com/iRealWorlds/licirom/blob/6c813f854c8c0c23058efc8958b8a9eb5dd22a86/Backend/API/Controllers/BidsController.cs#L97-L114

**Comment by irealworlds** [comment]
Frontend implementation in 029c780cedb8be043ba5fa9fd01e8802af1189c1
