### ISSUE TITLE
Profile settings

### ISSUE THREAD

**Issue by irealworlds** [iRealWorlds/licirom#6]
- [x] Change name
- [x] #7
- [ ] Download data (JSON)
- [x] Delete account

**Comment by trupples** [comment]
nu am intentionat sa fac acel issue

**Comment by trupples** [comment]
User delete: 3bab0994116477ff9316f634e33d13c3cf7840fb
User edit: 994697a9597178726ec2fd45b5bc7560145a64c2
Password change: 5943cc9430c9804da0a1bcc9064076ccec3d7075
